/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenubarItem } from "./components/menubar/menubar";
export { MenubarItem } from "./components/menubar/menubar";
export namespace Components {
    /**
     * Menubar component. Each item can have a menu with subitems or a sub-menubar.
     * @cssprop {--zanit-menubar-bg-color} Background color of the menubar.
     * @cssprop {--zanit-menubar-fg-color} Text color of the menubar.
     * @cssprop {--zanit-menubar-secondary-color} Secondary color of the menubar. Used for decorations and texts of different color.
     * @cssprop {--zanit-menubar-max-width} Maximum width of the menubar.
     */
    interface ZanitMenubar {
        /**
          * ID of the current active item.
         */
        "current": string | undefined;
        /**
          * The data to build the menu (as an array of `MenuItem` or a JSON array) or the url to fetch to retrieve it.
         */
        "data": Promise<MenubarItem[]> | MenubarItem[] | URL | string;
    }
}
declare global {
    /**
     * Menubar component. Each item can have a menu with subitems or a sub-menubar.
     * @cssprop {--zanit-menubar-bg-color} Background color of the menubar.
     * @cssprop {--zanit-menubar-fg-color} Text color of the menubar.
     * @cssprop {--zanit-menubar-secondary-color} Secondary color of the menubar. Used for decorations and texts of different color.
     * @cssprop {--zanit-menubar-max-width} Maximum width of the menubar.
     */
    interface HTMLZanitMenubarElement extends Components.ZanitMenubar, HTMLStencilElement {
    }
    var HTMLZanitMenubarElement: {
        prototype: HTMLZanitMenubarElement;
        new (): HTMLZanitMenubarElement;
    };
    interface HTMLElementTagNameMap {
        "zanit-menubar": HTMLZanitMenubarElement;
    }
}
declare namespace LocalJSX {
    /**
     * Menubar component. Each item can have a menu with subitems or a sub-menubar.
     * @cssprop {--zanit-menubar-bg-color} Background color of the menubar.
     * @cssprop {--zanit-menubar-fg-color} Text color of the menubar.
     * @cssprop {--zanit-menubar-secondary-color} Secondary color of the menubar. Used for decorations and texts of different color.
     * @cssprop {--zanit-menubar-max-width} Maximum width of the menubar.
     */
    interface ZanitMenubar {
        /**
          * ID of the current active item.
         */
        "current"?: string | undefined;
        /**
          * The data to build the menu (as an array of `MenuItem` or a JSON array) or the url to fetch to retrieve it.
         */
        "data"?: Promise<MenubarItem[]> | MenubarItem[] | URL | string;
    }
    interface IntrinsicElements {
        "zanit-menubar": ZanitMenubar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Menubar component. Each item can have a menu with subitems or a sub-menubar.
             * @cssprop {--zanit-menubar-bg-color} Background color of the menubar.
             * @cssprop {--zanit-menubar-fg-color} Text color of the menubar.
             * @cssprop {--zanit-menubar-secondary-color} Secondary color of the menubar. Used for decorations and texts of different color.
             * @cssprop {--zanit-menubar-max-width} Maximum width of the menubar.
             */
            "zanit-menubar": LocalJSX.ZanitMenubar & JSXBase.HTMLAttributes<HTMLZanitMenubarElement>;
        }
    }
}
